/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aritmatika.sederhana;

/**
 *
 * @author Shelin
 */
public class Frame1 extends javax.swing.JFrame {

    String jns = "";
    int jml;
    
    public Frame1() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        ket = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        b4 = new javax.swing.JLabel();
        bil1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        thasil = new javax.swing.JTextArea();
        bil2 = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        b3 = new javax.swing.JLabel();
        bil3 = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        jLabel8.setText("jLabel8");

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 20, 172, 21);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 70, 93, 16);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian", " " }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jPanel1.add(jenis);
        jenis.setBounds(219, 60, 161, 30);

        panel.setBackground(new java.awt.Color(153, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 2, 12))); // NOI18N
        panel.setLayout(null);
        panel.add(ket);
        ket.setBounds(120, 30, 147, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Jumlah Bilangan");
        panel.add(jLabel4);
        jLabel4.setBounds(20, 90, 93, 16);

        b1.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        b1.setText("Bilangan 1");
        panel.add(b1);
        b1.setBounds(20, 130, 55, 23);

        b2.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        b2.setText("Bilangan 2");
        panel.add(b2);
        b2.setBounds(20, 170, 55, 23);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil);
        pilihanbil.setBounds(180, 80, 147, 30);

        b4.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        b4.setText("Bilangan 4");
        panel.add(b4);
        b4.setBounds(20, 250, 55, 23);

        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        panel.add(bil1);
        bil1.setBounds(180, 120, 147, 30);

        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(180, 280, 84, 23);

        thasil.setColumns(20);
        thasil.setRows(5);
        jScrollPane1.setViewportView(thasil);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(170, 310, 197, 90);
        panel.add(bil2);
        bil2.setBounds(180, 160, 147, 30);
        panel.add(bil4);
        bil4.setBounds(180, 240, 147, 30);

        b3.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        b3.setText("Bilangan 3");
        panel.add(b3);
        b3.setBounds(20, 210, 55, 23);
        panel.add(bil3);
        bil3.setBounds(180, 200, 147, 30);

        jPanel1.add(panel);
        panel.setBounds(30, 110, 380, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 540);

        setSize(new java.awt.Dimension(455, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(bil1.getText().toString());
        a2 = Double.parseDouble(bil2.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml==2){
                hsl = a1 + a2;
                thasil.setText(""+ a1 +" + " + a2 + " = " + hsl);
            }
            if(jml==3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 + a2 + a3;
                thasil.setText(""+ a1 +" + "+ a2 + " + " + a3 + " = "+hsl);
            }
            if(jml==4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+ a1 +" + "+ a2 + " + " + a3 + " + "+ a4 +" = "+hsl);
            }
    }//GEN-LAST:event_jButton1ActionPerformed
        if(jns.equals("Pengurangan")){
            if(jml==2){
                hsl = a1 - a2;
                thasil.setText(""+ a1 +" - " + a2 + " = " + hsl);
            }
            if(jml==3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 - a2 - a3;
                thasil.setText(""+ a1 +" - "+ a2 + " - " + a3 + " = "+hsl);
            }
            if(jml==4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                thasil.setText(""+ a1 +" - "+ a2 + " - " + a3 + " - "+ a4 +" = "+hsl);
            }
        }
        if(jns.equals("Perkalian")){
            if(jml==2){
                hsl = a1 * a2;
                thasil.setText(""+ a1 +" x " + a2 + " = " + hsl);
            }
            if(jml==3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 * a2 * a3;
                thasil.setText(""+ a1 +" x "+ a2 + " x " + a3 + " = "+hsl);
            }
            if(jml==4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                thasil.setText(""+ a1 +" x "+ a2 + " x " + a3 + " x "+ a4 +" = "+hsl);
            }
        }
        if(jns.equals("Pembagian")){
            if(jml==2){
                hsl = a1 / a2;
                thasil.setText(""+ a1 +" : " + a2 + " = " + hsl);
            }
            if(jml==3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 / a2 / a3;
                thasil.setText(""+ a1 +" : "+ a2 + " : " + a3 + " = "+hsl);
            }
            if(jml==4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                thasil.setText(""+ a1 +" : "+ a2 + " : " + a3 + " : "+ a4 +" = "+hsl);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    private javax.swing.JTextArea thasil;
    // End of variables declaration//GEN-END:variables

    private void setJenis() {
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns = "penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
       
    }

    private void getJumlah() {
        if(pilihanbil.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml=2;
        }
        else if(pilihanbil.getSelectedItem().equals("3")){
            bil3.setVisible(true);
            b3.setVisible(true);
            bil4.setVisible(false);
            b4.setVisible(false);
            jml=3;
        }
        else if(pilihanbil.getSelectedItem().equals("4")){
            bil3.setVisible(true);
            b3.setVisible(true);
            bil4.setVisible(true);
            b4.setVisible(true);
            jml=4;
        }
    }
}
